import assert from 'node:assert/strict'; import fs from 'node:fs'; import path from 'node:path'; import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'); const r=path.join(root,'SafariExtension','Resources');
const m=JSON.parse(fs.readFileSync(path.join(r,'manifest.json'),'utf8'));
assert.equal(m.manifest_version,2); assert.equal(m.content_scripts[0].all_frames,true); assert.deepEqual(m.content_scripts[0].js,['surface-engine.js','content.js']);
for(const f of ['manifest.json','background.js','surface-engine.js','content.js','popup.html','popup.css','popup.js','theme.css']) assert.ok(fs.existsSync(path.join(r,f)),f);
const c=fs.readFileSync(path.join(r,'content.js'),'utf8');
for(const s of ['MutationObserver','shadowRoot','::before','::after','ensureReadableAccent','isSimpleMonochromeSvg']) assert.ok(c.includes(s),s);
const css=fs.readFileSync(path.join(r,'theme.css'),'utf8');
assert.doesNotMatch(css,/darkgrid-(?:frost|glow)::(?:before|after)/); assert.doesNotMatch(css,/backdrop-filter|mix-blend-mode:\s*screen/i); assert.doesNotMatch(css,/background-color:\s*transparent\s*!important/i);
assert.match(css,/data-darkgrid-before-surface/); assert.match(css,/data-darkgrid-svg-fill/);
const p=fs.readFileSync(path.join(r,'popup.js'),'utf8'); assert.match(p,/EXCLUDED/); assert.doesNotMatch(p,/sendMessage/); assert.match(p,/setTimeout\(.*90/s);
console.log('extension validation passed');
