(() => {
  const MEDIA_TAGS = new Set(["IMG", "VIDEO", "CANVAS", "PICTURE", "IFRAME", "OBJECT", "EMBED"]);
  function clamp(value,min,max){return Math.min(max,Math.max(min,value));}
  function parseRgbComponent(token){const t=String(token||"").trim();return t.endsWith("%")?clamp(Math.round((parseFloat(t)/100)*255),0,255):clamp(Math.round(parseFloat(t)),0,255);}
  function parseAlphaComponent(token){if(token==null||token==="")return 1;const t=String(token).trim();return t.endsWith("%")?clamp(parseFloat(t)/100,0,1):clamp(parseFloat(t),0,1);}
  function parseCssColor(value){const text=String(value||"").trim().toLowerCase();if(!text||text==="transparent"||text==="none")return null;const rgb=text.match(/^rgba?\(\s*([+-]?[\d.]+%?)[,\s]+([+-]?[\d.]+%?)[,\s]+([+-]?[\d.]+%?)(?:\s*[,/]\s*([+-]?[\d.]+%?))?\s*\)$/i);if(rgb)return{r:parseRgbComponent(rgb[1]),g:parseRgbComponent(rgb[2]),b:parseRgbComponent(rgb[3]),a:parseAlphaComponent(rgb[4])};const c=text.match(/^color\(\s*(?:srgb|display-p3)\s+([+-]?[\d.]+)\s+([+-]?[\d.]+)\s+([+-]?[\d.]+)(?:\s*\/\s*([+-]?[\d.]+%?))?\s*\)$/i);if(c)return{r:clamp(Math.round(parseFloat(c[1])*255),0,255),g:clamp(Math.round(parseFloat(c[2])*255),0,255),b:clamp(Math.round(parseFloat(c[3])*255),0,255),a:parseAlphaComponent(c[4])};return null;}
  function relativeLuminance(rgb){const ch=[rgb.r,rgb.g,rgb.b].map(x=>{const v=clamp(x,0,255)/255;return v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4)});return .2126*ch[0]+.7152*ch[1]+.0722*ch[2];}
  function perceivedBrightness(rgb){return .2126*rgb.r+.7152*rgb.g+.0722*rgb.b;}
  function mixRgb(base,accent,amount){const r=clamp(amount,0,1);return{r:Math.round(base.r*(1-r)+accent.r*r),g:Math.round(base.g*(1-r)+accent.g*r),b:Math.round(base.b*(1-r)+accent.b*r)};}
  function formatRgb(rgb,alpha=1){const r=clamp(Math.round(rgb.r),0,255),g=clamp(Math.round(rgb.g),0,255),b=clamp(Math.round(rgb.b),0,255),a=clamp(Number(alpha),0,1);return a>=.999?`rgb(${r}, ${g}, ${b})`:`rgba(${r}, ${g}, ${b}, ${Number(a.toFixed(3))})`;}
  function rgbToHex(rgb){const p=v=>clamp(Math.round(v),0,255).toString(16).padStart(2,"0").toUpperCase();return`#${p(rgb.r)}${p(rgb.g)}${p(rgb.b)}`;}
  function ensureReadableAccent(rgb,min=.22){if(relativeLuminance(rgb)>=min)return{...rgb};let lo=0,hi=1,best={...rgb};for(let i=0;i<14;i++){const m=(lo+hi)/2,c=mixRgb(rgb,{r:255,g:255,b:255},m);if(relativeLuminance(c)>=min){best=c;hi=m}else lo=m}return best;}
  function buildSurfaceColors(original,accent){const n=perceivedBrightness(original)/255,l=relativeLuminance(original),level=clamp(Math.round(2+Math.pow(n,.82)*40),2,42),neutral={r:level,g:level,b:level},frost=mixRgb(neutral,accent,l>.6?.105:l>.18?.085:.06),a=clamp(original.a==null?1:original.a,0,1);return{normal:formatRgb(neutral,a),frost:formatRgb(frost,a),alpha:a};}
  function buildPageFrostColor(accent){return formatRgb(mixRgb({r:0,g:0,b:0},accent,.03));}
  function buildForegroundColor(original){return !original||relativeLuminance(original)<.34?"#E7E7E7":formatRgb(original,original.a??1);}
  function isMediaElement(el){return Boolean(el?.tagName&&MEDIA_TAGS.has(el.tagName));}
  function hasRasterBackground(v){return/url\s*\(/i.test(String(v||""));}
  function hasGradientBackground(v){return/(?:linear|radial|conic)-gradient\s*\(/i.test(String(v||""));}
  function hasVisibleBorder(s){if(!s)return false;return["Top","Right","Bottom","Left"].some(side=>{const width=parseFloat(s[`border${side}Width`]||"0"),style=String(s[`border${side}Style`]||"none"),raw=String(s[`border${side}Color`]||"").trim().toLowerCase(),color=parseCssColor(raw);return width>0&&!['none','hidden'].includes(style)&&raw!=="transparent"&&(!color||color.a>.02);});}
  function rewriteBoxShadow(v){const t=String(v||"");if(!t||t==='none')return null;return t.replace(/(rgba?\([^)]*\)|color\([^)]*\))/gi,x=>{const c=parseCssColor(x);if(!c)return x;const z=relativeLuminance(c)>.45?24:8;return formatRgb({r:z,g:z,b:z},Math.min(c.a??1,.55));});}
  function hasDirectText(el){if(!el?.childNodes)return false;if(["INPUT","TEXTAREA","SELECT","OPTION","BUTTON"].includes(el.tagName))return true;return[...el.childNodes].some(n=>n.nodeType===3&&String(n.nodeValue||"").trim());}
  function pseudoIsRenderable(s){if(!s)return false;const c=String(s.content||"").trim();return c!==""&&c!=="none"&&c!=="normal";}
  function isSimpleMonochromeSvg(svg){if(!svg||svg.tagName!=="SVG"||svg.querySelector("image,foreignObject,linearGradient,radialGradient,pattern,filter,mask,clipPath"))return false;const p=[...svg.querySelectorAll("path,rect,circle,ellipse,line,polyline,polygon")];if(!p.length||p.length>16)return false;let painted=0;for(const n of p){const s=getComputedStyle(n);for(const prop of['fill','stroke']){const c=parseCssColor(s[prop]);if(c&&c.a>.02){painted++;if(Math.max(c.r,c.g,c.b)-Math.min(c.r,c.g,c.b)>34)return false;}}}return painted>0;}
  globalThis.DarkgridSurfaceEngine=Object.freeze({parseCssColor,relativeLuminance,perceivedBrightness,formatRgb,rgbToHex,ensureReadableAccent,buildSurfaceColors,buildPageFrostColor,buildForegroundColor,isMediaElement,hasRasterBackground,hasGradientBackground,hasVisibleBorder,rewriteBoxShadow,hasDirectText,pseudoIsRenderable,isSimpleMonochromeSvg});
})();
